### ISSUE TITLE
Error edit Extensions Discount

### ISSUE THREAD

**Issue by hieuna** [lanhktc/s-cart#13]
Hi,
I'm edit Extensions Discount but error. how can fix it? Thanks
![Screenshot_1](https://user-images.githubusercontent.com/11455228/54099816-be44c980-43ed-11e9-872e-d7c3e074058b.png)

**Comment by lanhktc** [comment]
- in file app/Admin/routes.php, find line 
`    $router->resource('shop_discount', Extensions\Total\DiscountController::class)->names('configDiscount')->names('discountControl');` . Remove `**->names('configDiscount')**`
- in file app/Extensions/Total/Controller/Discount.php, replace "configDiscount.index" by "discountControl.index"
