### ISSUE TITLE
Admn: compact(): Undefined variable: max_order

### ISSUE THREAD

**Issue by theejhay** [lanhktc/s-cart#14]
![Screenshot (223)](https://user-images.githubusercontent.com/5153785/54286126-8c756380-45a3-11e9-97e0-a59aac1d206c.png)

**Comment by lanhktc** [comment]
in file admin/HomeConroller.php, find `compact(['arrTotalsAmount_year', 'totals_month', 'months1', 'max_order']))`, remove `'totals_month',` and `, 'max_order'`

**Comment by theejhay** [comment]
**Thanks, it has been fixed.**
