### ISSUE TITLE
Custom style PAGINATION

### ISSUE THREAD

**Issue by hieuna** [lanhktc/s-cart#15]
Hi, I'm trying custom pagination style and html other (look image). But i can't find edit file pagination. You can help me? Thanks.
![Screenshot_2](https://user-images.githubusercontent.com/11455228/54290889-50132900-45de-11e9-906e-00c5649e711d.png)

**Comment by lanhktc** [comment]
Path file: vendor/laravel/framework/src/Illuminate/Pagination/resources/views

**Comment by hieuna** [comment]
Ok, Thanks.
