### ISSUE TITLE
Add to Cart

### ISSUE THREAD

**Issue by Aliazam513** [lanhktc/s-cart#16]
I have seen new updated Demo in which you update the Add to cart as (Add product to Cart Successfully)

i have already compile this please tell me which file i have to change to update this Add to cart funtionality

**Comment by lanhktc** [comment]
Pls wait next release

Vào 15:30, T.4, 20 Th3, 2019 Aliazam513 <notifications@github.com đã viết:

**Comment by Aliazam513** [comment]
Helo which file i need to update to add new  Add to cart functionality

**Comment by lanhktc** [comment]
Too many changes. pls download the source version of the latest version.
