### ISSUE TITLE
Broken non latin urls

### ISSUE THREAD

**Issue by yosirn** [lanhktc/s-cart#18]
the function geturl() returns an empty string for non latin languages and thus the product page is 404.

**Comment by lanhktc** [comment]
Find app/Scart/Helpers/Helper.php:
replace 
`array('/[^a-zA-Z0-9\s-]/', '/[\s-]+|[-\s]+|[--]+/', '/^[-\s_]|[-_\s]$/'),`
by
`array('/[\'\/~`\!@#\$%\^&\*\(\)\+=\{\}\[\]\|;:"\<\>,\.\?\\\]/', '/[\s-]+|[-\s]+|[--]+/', '/^[-\s_]|[-_\s]$/'),`
