### ISSUE TITLE
Use of undefined constant SITE_THEME

### ISSUE THREAD

**Issue by yosirn** [lanhktc/s-cart#21]
I get this error on my production server but not on the local server  (same php version PHP 7.2.17)

`Use of undefined constant SITE_THEME - assumed 'SITE_THEME' (this will throw an Error in a future version of PHP)`

**Comment by lanhktc** [comment]
s-cart version?
can you give me image about error

**Comment by yosirn** [comment]
S-cart 3.0.0
This happened after I immigrated my shop 

![image](https://user-images.githubusercontent.com/10193377/58021934-99b34f00-7b0c-11e9-9cf3-b55749088bf4.png)

**Comment by lanhktc** [comment]
I need more infomation:
- Source code from : composer, github, or sourcefore, google dirive
- You use virtual host, 127.0.0.1:8000 (php artisan serve) or sub path (http://localhost/path-scart/public)
Try: `php artisan config:clear`, `php artisan cache:clear`

**Comment by yosirn** [comment]
Solved,
the problem occurs because  I removed English (en) from language table
