### ISSUE TITLE
Field Type divide does not exist 

### ISSUE THREAD

**Issue by maheshbhattaraai** [lanhktc/s-cart#22]
While Editing on config globals gives filed type divide does not exist error.

**Comment by lanhktc** [comment]
Give me error message or screen error

**Comment by maheshbhattaraai** [comment]
[image: Screenshot_1.jpg]

**Comment by maheshbhattaraai** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/34735076/59729708-5f4de680-925f-11e9-8285-e176c8ea086a.jpg)

**Comment by MichleLI** [comment]
I have also a same error!
![image](https://user-images.githubusercontent.com/45660446/61993735-a3c07380-b0a2-11e9-9a47-b982de5f6872.png)

**Comment by MichleLI** [comment]
I fixed this issue
change from 'divide' to 'divider'
![image](https://user-images.githubusercontent.com/45660446/64492091-ac5fb880-d2a2-11e9-97b0-4dbaf9584bb2.png)
