### ISSUE TITLE
images not showing in admin Panel

### ISSUE THREAD

**Issue by matatashadrack** [lanhktc/s-cart#28]
![image](https://user-images.githubusercontent.com/42380854/63212211-8878df00-c109-11e9-87c5-86ba29c3037e.png)
Images are not showing i admin panel but they are okay in the website,kindly help

**Comment by lanhktc** [comment]
File .env, you check value of APP_URL

**Comment by matatashadrack** [comment]
> 
> 
> File .env, you check value of APP_URL

if **C:\xampp\htdocs\ofarm\s-cart\public** is my app path,how should it look like in the .env file?

**Comment by lanhktc** [comment]
S-cart/.env

Vào 20:21, CN, 18 Th8, 2019 Amos M Shadrack <notifications@github.com đã
viết:
