### ISSUE TITLE
Photos Can't Store on Public Folder

### ISSUE THREAD

**Issue by jobferrera** [lanhktc/s-cart#3]
Good day,

It can't store files of documents/website folders on my cpanel, yet i changed the permission Chmod -R 777 already.
Thank you!

Regards

**Comment by lanhktc** [comment]
> Good day,
> 
> It can't store files of documents/website folders on my cpanel, yet i changed the permission Chmod -R 777 already.
> Thank you!
> 
> Regards

Note, the directory structure must look like the one below:
--documents
----website
--------banner
--------category
--------...
--------thumb
--------------banner
--------------category
--------------...

**Comment by jobferrera** [comment]
Thanks sir for your reply,

Am I going to give documents folder 777 permission?
or just the website and thumb folder?

Thank you!

**Comment by jobferrera** [comment]
> > Good day,
> > It can't store files of documents/website folders on my cpanel, yet i changed the permission Chmod -R 777 already.
> > Thank you!
> > Regards
> 
> Note, the directory structure must look like the one below:
> --documents
> ----website
> --------banner
> --------category
> --------...
> --------thumb
> --------------banner
> --------------category
> --------------...

**Comment by jobferrera** [comment]
> > Good day,
> > It can't store files of documents/website folders on my cpanel, yet i changed the permission Chmod -R 777 already.
> > Thank you!
> > Regards
> 
> Note, the directory structure must look like the one below:
> --documents
> ----website
> --------banner
> --------category
> --------...
> --------thumb
> --------------banner
> --------------category
> --------------...

Thank you for your reply sir,,

nothing happens, yes the directory looks like the above illustration,
anyways on my cpanel i'm working with the directory below:

public_html/shopping ...
