### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by JFProgrammer** [lanhktc/s-cart#31]
How can I fix this bug, everything is set up correctly to set the password that works, but this and the other email services don't work.
If you have any mistake I'm sorry I'm Brazilian
![não acerto esse bug](https://user-images.githubusercontent.com/51108267/67103257-24bb7280-f19b-11e9-9ed9-abb820faae30.png)

**Comment by lanhktc** [comment]
Please find in files: 
- app\Http\Controlers\ShopCart.php
- app\Http\Controlers\ContentFront.php
- app\Http\Controlers\Auth\RegisterController.php
Replace "EmailTemplate" to "ShopEmailTemplate"
