### ISSUE TITLE
Cannot use object of type

### ISSUE THREAD

**Issue by JFProgrammer** [lanhktc/s-cart#33]
Sorry, but I found one more bug kkkk!
[BUG](https://user-images.githubusercontent.com/51108267/67108792-a0bab800-f1a5-11e9-883a-5a3ea89d437d.png)

**Comment by lanhktc** [comment]
> Sorry, but I found one more bug kkkk!
> [BUG](https://user-images.githubusercontent.com/51108267/67108792-a0bab800-f1a5-11e9-883a-5a3ea89d437d.png)

Replace $row->category() = $row->category

**Comment by lanhktc** [comment]
Pls download last release
