### ISSUE TITLE
Bug email

### ISSUE THREAD

**Issue by JFProgrammer** [lanhktc/s-cart#35]
![Screenshot_20191022-170655](https://user-images.githubusercontent.com/51108267/67327994-2ebcd880-f4ef-11e9-9ff4-ab4859fa9695.png)

**Comment by JFProgrammer** [comment]
What version is the s-cart bootstrap on? and how can i upgrade?

**Comment by lanhktc** [comment]
Front-end demo using Bootstrapv3.0.3. Static files app/public/templates/default.  
We dont support you upgrade or change version Bootstrap, but you can customize or create new template for yourselt.
https://s-cart.org/download/template.html
