### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by m2ura** [lanhktc/s-cart#36]
Hi,

How to change banner image to be full screen background image, I have been trying to do that with no success.

**Comment by JFProgrammer** [comment]
Hi friend, can I try to help you, what do you mean in full screen? Do you want it to be background or just for a certain size?

**Comment by m2ura** [comment]
Hi my guy, I want it to be background that covers the full width of the page, and must be right under navigation because now it is far from the navigation.
![cart](https://user-images.githubusercontent.com/13012135/67595288-94ff6080-f766-11e9-9748-909a52390865.png)

**Comment by m2ura** [comment]
And this is a banner

 @php
    $banners = \App\Models\ShopBanner::where('status', 1)->sort()->get()
  @endphp
 @if (!empty($banners))
 <section id="slider">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div id="slider-carousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              @foreach ($banners as $key => $banner)
              <li data-target="#slider-carousel" data-slide-to="{{ $key }}" class="{{ ($key)?'':'active' }}"></li>
              @endforeach
            </ol>
            <div class="carousel-inner">
               @foreach ($banners as $key => $banner)
                  <div class="item {{ ($key)?'':'active' }}">
                    <div class="col-sm-12">
                      <img src="{{ $banner->image }}" class="girl img-responsive" alt="" />
                    </div>
                  </div>
               @endforeach
            </div>
            
          </div>

        </div>
      </div>
    </div>
  </section>
@endif

**Comment by JFProgrammer** [comment]
![image](https://user-images.githubusercontent.com/51108267/67596622-8a7da080-f73f-11e9-90ba-b9839cac3501.png)

Hello friend, for you to change the width you need to come in this folder and look for "s-cart\public\ css\app.css"

In this css, you search for "carousel-indicators"

will have all the carrousel css

the blade to show the carousel is in this path "s-cart\resources\views\block\ banner_image.blade.php"

**Comment by m2ura** [comment]
Thank you very much my guy, much appreciated.
