### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by Aliazam513** [lanhktc/s-cart#4]
Helo i have run the command
composer create-project lanhktc/s-cart to install the system at localhost

first i tried with this url but its not working 
http://localhost/s-cart/

after that i tried using url
http://localhost/s-cart/public/ it works fine 

![image](https://user-images.githubusercontent.com/47612695/52744620-0a733880-2fff-11e9-9228-a4e03bdf71ab.png)

but when i tried the admin login
http://localhost/s-cart/public/system_admin/auth/login 

it is always showing me this error while logging in 
![image](https://user-images.githubusercontent.com/47612695/52744675-2aa2f780-2fff-11e9-9839-182214caf493.png)

kindly please help me in this how do i solve this issue because i did not find the system_admin folder to solved it by myself please help
Thank you

**Comment by lanhktc** [comment]
Pls not use http://localhost/s-cart/public/
**2 options to you run s-cart on localhost:**
1- Not use vhost
- move to directory s-car (root folder)
- Run command "php artisan serve"
- Access to http://127.0.0.1:8000
Read document: https://s-cart.org/installation.html#localhost
2. Virtual host
- Pls point vhost to directory public
Example for Virtual host on window apache:
`<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host2.example.com
    DocumentRoot "C:\xampp\htdocs\s-cart/**public**"
    ServerName demoshop.local
    ErrorLog "logs/shop.com-error.log"
    CustomLog "logs/shop.com-access.log" common
</VirtualHost>`
After, access to your domain on local.

**Comment by Aliazam513** [comment]
Ok great Thank you so much for the help i have access the admin now 
and where to find the admin routes and admin panel all source code
and one last thing if i upload to my server in a folder then whats the procedure to live it better 
then admin panel will able to access or not ??

**Comment by Aliazam513** [comment]
![image](https://user-images.githubusercontent.com/47612695/52793357-5f5e8f80-308f-11e9-8640-159623893cd3.png)

now i am facing this issue while uploading in server as in folder /shop how reslove this as well

**Comment by lanhktc** [comment]
When release website on server, you need point virtual host to folder "public" of s-cart. You can find information on how to install the laravel website on your server type from google.

**Comment by Aliazam513** [comment]
i dont know how to do please kindly help contact me aazam513@gmail.com

**Comment by Aliazam513** [comment]
and please tell me how can i access and change something in system_admin folder 
because it is not available

**Comment by Aliazam513** [comment]
![image](https://user-images.githubusercontent.com/47612695/52806853-df92ee00-30ab-11e9-9233-fd304ab51f74.png)
 
and i am unable to get these images in admin panel in localhost i want to change the url how can i do that

**Comment by lanhktc** [comment]
For error image in admin, pls config in file .env:
APP_URL=http://localhost -> APP_URL=your-domain.
ex: APP_URL=http://127.0.0.1:8000

**Comment by Aliazam513** [comment]
![image](https://user-images.githubusercontent.com/47612695/52874740-3e239f00-3174-11e9-9126-d74858a5fa90.png)
 
i am still unable to get these thumbnails even after i have set the APP-URL
and please do provide me the information for server issue as well kindly
thank you

**Comment by lanhktc** [comment]
After change domain, you need run "php artisan serve" again

**Comment by Aliazam513** [comment]
![acacaq](https://user-images.githubusercontent.com/47612695/52898198-c057a600-31fc-11e9-8032-86f1ff596ffe.png)
![acacaqqq](https://user-images.githubusercontent.com/47612695/52898199-c0f03c80-31fc-11e9-97c5-de3acf6a9dd2.png)

Thank you and where do i change these names of site and S-cart admin??

**Comment by Aliazam513** [comment]
![acaaa](https://user-images.githubusercontent.com/47612695/52900584-834ddc80-3219-11e9-9c12-219e3d923e86.png)
and i want to change all footer content including copyrights as well how to do this as well??
