### ISSUE TITLE
Lỗi khi cập nhật hình ảnh trong admin

### ISSUE THREAD

**Issue by dottokuya** [lanhktc/s-cart#41]
E đang thử chạy trên localhost, mà khi muốn cập nhật hình ảnh sản phẩm hay danh mục đều bị lỗi object not found
![image](https://user-images.githubusercontent.com/55634529/68960919-bacad300-0803-11ea-9480-b0f663b3817d.png)

**Comment by lanhktc** [comment]
Bạn cần cấu hình vhost cho S-cart, thay vì sử dụng nó giống như 1 folder.
http://localhost/s-cart/public -> sai
http://s-cart.local -> đúng
Bạn tham khảo: https://s-cart.org/installation.html?lang=vi#vhost

**Comment by lanhktc** [comment]
Từ phiên bản 3.2.2, bạn cũng có thể truy cập S-Cart theo đường dẫn `http://localhost/s-cart/public`
https://s-cart.org/release-note.html?version=3.2
