### ISSUE TITLE
 Automatic Update

### ISSUE THREAD

**Issue by JFProgrammer** [lanhktc/s-cart#44]
Hello friend, I was wondering if you could automatically update only the modified files ...

because I am in an old version and I do not know how I will update because I already changed a lot and now I do not know what to do ...

**Comment by lanhktc** [comment]
Hi,
we are still trying to build a stable version of the structure, easy for maintenance and upgrading between future versions. And, we are expecting versions starting at 3.3.x
Please refer to: https://s-cart.org/upgrade-guide.html?version=3.2
