### ISSUE TITLE
I could not upload the site

### ISSUE THREAD

**Issue by JFProgrammer** [lanhktc/s-cart#45]
Hello friend, I came to you for help I can not put the server on webhost000 to test ... all the settings are down ...

![image](https://user-images.githubusercontent.com/51108267/69573616-39163a80-0fa5-11ea-8282-94c7591a3005.png)
![image](https://user-images.githubusercontent.com/51108267/69573677-5ba85380-0fa5-11ea-926f-ed9e1fcbc75f.png)
![image](https://user-images.githubusercontent.com/51108267/69573702-682cac00-0fa5-11ea-9abb-9f089d06df33.png)
![image](https://user-images.githubusercontent.com/51108267/69574063-0d478480-0fa6-11ea-86d1-a36df4f5c113.png)

**Comment by lanhktc** [comment]
- To display error, in file .env, pls set APP_DEBUG=false=> APP_DEBUG=true
- Step 2: Make sure the directories and its subdirectories are writable: storage,  vendor, public/data
https://s-cart.org/installation.html
