### ISSUE TITLE
Security module

### ISSUE THREAD

**Issue by JFProgrammer** [lanhktc/s-cart#47]
Hello friend, I came to ask you for help installing this module: https://github.com/michaeldouglas/laravel-pagseguro

I wanted you to give me a light on how to implement this module, I'm not very good at laravel so I came to ask you for help ...

Taking advantage of it, I've already worked on every Banner css and I can't increase its size, could you help me with that too?

Thankful!

**Comment by lanhktc** [comment]
Sorry, we don't know much about this package, so we cannot support you.
To develop S-Cart at a deep level, like installing framwork packages, you need to have some knowledge about laravel framework.
