### ISSUE TITLE
logo upload error

### ISSUE THREAD

**Issue by m2ura** [lanhktc/s-cart#48]
Hello,

I get an error when uploading a logo image. Version 3.3

![upload error](https://user-images.githubusercontent.com/13012135/69915026-2becc600-1453-11ea-9b4e-8f51bd77dd57.png)

But post reqeust is fine

![error](https://user-images.githubusercontent.com/13012135/69915052-6a828080-1453-11ea-8dbe-17589494e162.png)

**Comment by m2ura** [comment]
Logs
[previous exception] [object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getThumb() on null at /var/www/laravel/bagisto/app/Library/ShoppingCart/Cart.php:489)
[stacktrace]
#0 /var/www/laravel/shop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(239): App\\Library\\ShoppingCart\\Cart::getListCart()
#1 /var/www/laravel/shop/storage/framework/views/6c29d4c341810760ed71266bf3b2dec126382de6.php(2): Illuminate\\Support\\Facades\\Facade::__callStatic('getListCart', Array)
#2 /var/www/laravel/shop/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/var/www/larave...')
#3 /var/www/laravel/shop/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/var/www/larave...', Array)
#4 /var/www/laravel/shop/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate\\View\\Engines\\CompilerEngine->get('/var/www/larave...', Array)
#5 /var/www/laravel/shop/vendor/laravel/framework/src/Illuminate/View/View.php(143): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get('/var/www/larave...', Array)
#6 /var/www/laravel/shop/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\\View\\View->getContents()
#7 /var/www/laravel/shop/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#8 /var/www/laravel/shop/storage/framework/views/ce0ff124c3494bf4259ca3a34da6b34dcd0c6166.php(71): Illuminate\\View\\View->render()

**Comment by lanhktc** [comment]
For error upload image, you can ref at topic : https://github.com/UniSharp/laravel-filemanager/issues/475

**Comment by m2ura** [comment]
Decided to downlaod the full version of version 3.3, but even though I ran all the permissions 
sudo chmod -R 777 vendor
sudo chmod -R 777 storage
sudo chmod -R 777 public/data

And sudo chown -Rf $USER:www-data *

I get the below
![3 3](https://user-images.githubusercontent.com/13012135/70003601-4f576400-156c-11ea-9b82-8444d611ec86.png)

**Comment by m2ura** [comment]
Fixed version 3.3
