### ISSUE TITLE
CKeditor

### ISSUE THREAD

**Issue by Aliazam513** [lanhktc/s-cart#5]
Helo 
i have uploaded this s-cart to my server successfully but when i click to edit the product it always showing me the error how to solve this issue kindly tell me please
![image](https://user-images.githubusercontent.com/47612695/53369405-f4edff00-396c-11e9-8ad4-49be6814b99f.png)

**Comment by lanhktc** [comment]
Rename file resource/views/admin/ckeditor.balde.php to CKEditor.balde.php

**Comment by Aliazam513** [comment]
Thank you so much
