### ISSUE TITLE
signup bug

### ISSUE THREAD

**Issue by hmsakran** [lanhktc/s-cart#54]
found bug on user register, detail :
file : app/Http/Controller/Auth/RegisterController.php
on create function,
i make small change but fix the bug.

$dataMap = [
            'first_name' => $data['reg_first_name'],
            'last_name' => $data['reg_last_name']??'',
            'email' => $data['reg_email'],
            'password' => bcrypt($data['reg_password']),
            'phone' => $data['reg_phone']??null,
            'address1' => $data['reg_address1'],
            'address2' => $data['reg_address2']??'',
            'country' => $data['reg_country']??'VN',
            'group' => $data['reg_group']??1,
            // 'birthday' => $data['reg_birthday'],
            'sex' => $data['reg_sex']??0,
            'postcode' => $data['reg_postcode']??null,
        ];
        if(!empty($data['reg_birthday'])){
            $dataMap['birthday'] = $data['reg_birthday'];    
        }

**Comment by hmsakran** [comment]
this error just happen when i try to register user n CONFIG CUSTOMER on birtday UNCHECK.
u got 500 internal server error.

but when u CHECK birtday on CONFIG CUSTOMER error not showup.

**Comment by lanhktc** [comment]
Give me message log

**Comment by hmsakran** [comment]
[2020-01-02 09:20:22] local.ERROR: Undefined index: reg_birthday {"exception":"[object] (ErrorException(code: 0): Undefined index: reg_birthday at /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/app/Http/Controllers/Auth/RegisterController.php:108)
[stacktrace]
#0 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/app/Http/Controllers/Auth/RegisterController.php(108): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/Volumes/Macint...', 108, Array)
#1 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Foundation/Auth/RegistersUsers.php(33): App\\Http\\Controllers\\Auth\\RegisterController->create(Array)
#2 [internal function]: App\\Http\\Controllers\\Auth\\RegisterController->register(Object(Illuminate\\Http\\Request))
#3 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#4 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('register', Array)
#5 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Auth\\RegisterController), 'register')
#6 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#7 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#8 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/app/Http/Middleware/RedirectIfAuthenticated.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/app/Http/Middleware/Currency.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\Currency->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/app/Http/Middleware/Localization.php(35): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\Localization->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#30 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#31 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#32 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#33 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/spatie/laravel-pjax/src/Middleware/FilterIfPjax.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Spatie\\Pjax\\Middleware\\FilterIfPjax->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#50 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#51 /Volumes/Macintosh HD 2/CODE ZONE/WEBSITE/LARAVEL/GEGAWAAN/s-cart/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#52 {main}
"}

**Comment by lanhktc** [comment]
you try download last full version from https://s-cart.org/download.html
