### ISSUE TITLE
File Manager from frontend without admin login.

### ISSUE THREAD

**Issue by nitinkrsing** [lanhktc/s-cart#58]
First, it's not an issue, I am just stuck at something.
Second, thank you for making such an open-source eCommerce platform.

I am using s-cart to create a bartering web app. For that, I have added the form for "Add Product" in the customer/member account area, but my problem is file-manager. It loads the Admin login screen in the file-manager window.

Can you please tell me how to disable/remove Admin auth from file-manager in frontend?

**Comment by lanhktc** [comment]
Try copy s-cart\app\Admin\Routes\file_manager.php to s-cart\routes\component\file_manager.php.
Then, use your-domain.com/uploads
