### ISSUE TITLE
Edit products price_promotion error 

### ISSUE THREAD

**Issue by jodaches** [lanhktc/s-cart#59]
Hello, I'm starting a project based on s-cart and it's really awesome, appreciate a lot your wok. 

I got an exception **trying to get property of non-object** when saving products 

To solve it I changed it from 
_value="{!! old('price_promotion',$product->promotionPrice->price_promotion) !!}"_
To
_value="{!! old('price_promotion') ?? $product->promotionPrice->price_promotion !!}_

product_edit.blade.php **line 403**

To reproduce it:
- Enter to edit a product with no price promotion
- Add price promotion
- Leave empty one required field like name or content

Version 3.4.3

Regards

**Comment by lanhktc** [comment]
Thanks reported.
This bug has fixed in v4
