### ISSUE TITLE
one last issue i am facing 

### ISSUE THREAD

**Issue by Aliazam513** [lanhktc/s-cart#6]
This pictures on front web and thumbnails on admin are not working how to solve this
![image](https://user-images.githubusercontent.com/47612695/53397515-1ed50f00-39c9-11e9-96f1-7e3ae05c0f18.png)

![image](https://user-images.githubusercontent.com/47612695/53397534-28f70d80-39c9-11e9-8633-08b3bbc09985.png)

**Comment by lanhktc** [comment]
You need set permission writable for directory public/documents/website and all children categories of its

**Comment by Aliazam513** [comment]
it is now remove all the css 
![image](https://user-images.githubusercontent.com/47612695/53399022-dddef980-39cc-11e9-856c-426b4310c7f7.png)

**Comment by Aliazam513** [comment]
![image](https://user-images.githubusercontent.com/47612695/53399464-d8ce7a00-39cd-11e9-8e2a-1908c9d6649d.png)
