### ISSUE TITLE
bug shop_product_detail.blade.php It's not closing div tag in recomended items

### ISSUE THREAD

**Issue by jodaches** [lanhktc/s-cart#61]
Hello guys.

I noticed wrong html structure, because this line

https://github.com/lanhktc/s-cart/blob/master/resources/views/templates/default/screen/shop_product_detail.blade.php#L192

Changed to this, to close the div in last item. 
```
@if ($key % 4 == 3 || $key == count($productsToCategory) -1 )
  </div>
@endif
```
My Version 3.4.3

Regards

**Comment by lanhktc** [comment]
Thanks!
