### ISSUE TITLE
Admin Order edit

### ISSUE THREAD

**Issue by Aliazam513** [lanhktc/s-cart#7]
please tell me how to solve this issue 
you can see in order editing i am facing double subtotal double shipping only shipping standard is actived 
and double discount please tell me how do i reslove this

![acaca](https://user-images.githubusercontent.com/47612695/53586749-a037c780-3baa-11e9-907f-106bc0d9e784.png)

**Comment by Aliazam513** [comment]
These are my total,sub-total.shipping charges other ones i dont know why they are appearing please help me how do i solve this
![acaca24](https://user-images.githubusercontent.com/47612695/53587380-053fed00-3bac-11e9-89c2-506f82c6b081.png)

**Comment by lanhktc** [comment]
Tell me the steps you took to appear this error message

**Comment by Aliazam513** [comment]
i was just ordered an item from front and when i have seen the order from admin panel i am facing this double entries i will send you my cpanel on your email if you can solve this issue please let me know

**Comment by lanhktc** [comment]
Maybe when you empty  data in shop_order table, you didn't delete shop_order_total table. So the order will be duplicated when the new order_id number coincides with old order_id available in shop_order_total.
