### ISSUE TITLE
error create new page 'scart.cms_page'

### ISSUE THREAD

**Issue by hieuna** [lanhktc/s-cart#8]
Hi,
I create new page but error.
 QueryException In Connection.php line 664 :
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'scart.cms_page' doesn't exist (SQL: select count(*) as aggregate from `cms_page` where `uniquekey` = dsddđ and `id` )
How fix it? thanks

**Comment by lanhktc** [comment]
Find line 125, app/Admin/controllers/ShopPageController.php, replace "unique:cms_page" to "unique:shop_page".
This error will fix in next version. Thanks.
